export const technologyOptions = [
  { value: 'csharp', label: 'C#' },
  { value: 'cplusplus', label: 'C++' },
  { value: 'go', label: 'Go' },
  { value: 'java', label: 'Java' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'php', label: 'PHP' },
  { value: 'python', label: 'Python' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'swift', label: 'Swift' },
  { value: 'typescript', label: 'Typescript' },
  { value: 'angularjs', label: 'Angular' },
  { value: 'nextjs', label: 'Next.js' },
  { value: 'flask', label: 'Flask' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'nodejs', label: 'Node.js' },
  { value: 'rails', label: 'Rails' },
  { value: 'react', label: 'React' },
  { value: 'vuejs', label: 'Vue.js' },
  { value: 'django', label: 'Django' },
  { value: 'express', label: 'Express' },
  { value: 'nuxtjs', label: 'Nuxt' },
  { value: 'svelte', label: 'Svelte' },
  { value: 'tailwindcss', label: 'Tailwind' },
  { value: 'sass', label: 'Sass' },
  { value: 'html5', label: 'HTML' },
  { value: 'css3', label: 'CSS' },
];

export const rolesOptions = [
  { value: 'project_manager', label: 'Project Manager' },
  { value: 'scrum_master', label: 'Scrum Master' },
  { value: 'developer', label: 'Developer' },
  { value: 'qa_engineer', label: 'QA Engineer' },
  { value: 'devops_engineer', label: 'DevOps Engineer' },
  { value: 'architect', label: 'Architect' },
  { value: 'technical_lead', label: 'Technical Lead' },
  { value: 'product_owner', label: 'Product Owner' },
  { value: 'frontend developer', label: 'Frontend Developer' },
  { value: 'backend developer', label: 'Backend Developer' },
  { value: 'fullstack developer', label: 'Fullstack Developer' },
  { value: 'web developer', label: 'Web Developer' },
  { value: 'web developer', label: 'Web Developer' },
  { value: 'system administrator', label: 'System Administrator' },
  { value: 'database administrator', label: 'Database Administrator' },
];
